/**/controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    franka_robot_state_broadcaster:
      type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster

/**/franka_robot_state_broadcaster:
  ros__parameters:
    arm_id: panda

/**/joint_trajectory_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)joint_1
      - $(var tf_prefix)joint_2
      - $(var tf_prefix)joint_3
      - $(var tf_prefix)joint_4
      - $(var tf_prefix)joint_5
      - $(var tf_prefix)joint_6
      - $(var tf_prefix)joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      $(var tf_prefix)joint_1: {trajectory: 0.2, goal: 0.1}
      $(var tf_prefix)joint_2: {trajectory: 0.2, goal: 0.1}
      $(var tf_prefix)joint_3: {trajectory: 0.2, goal: 0.1}
      $(var tf_prefix)joint_4: {trajectory: 0.2, goal: 0.1}
      $(var tf_prefix)joint_5: {trajectory: 0.2, goal: 0.1}
      $(var tf_prefix)joint_6: {trajectory: 0.2, goal: 0.1}
      $(var tf_prefix)joint_7: {trajectory: 0.2, goal: 0.1}
